### PR TITLE
[Gen 3] Fix Emerald egg generator displaying 0 advances

### LINKED ISSUE #201: Emerald Egg Generator Displaying 0 Advances
Tested on the windows appveyor build of 14eb361d9509c108bab6e0db2dd3c96ef3478880
Appears to affect all methods of emerald eggs only

To reproduce: search with any params in the Emerald Egg generator

### PR DESCRIPTION
**Pull request by Real96**
Fix #201

### CODE REVIEW

File: Source/Forms/Models/Gen3/EggModel3.cpp [hunk 1]
```diff
@@ -62,7 +62,14 @@ QVariant EggModel3::data(const QModelIndex &index, int role) const
...
         case 1:
-            return state.getGenerateAdvance();
+            switch (method)
+            {
+            case Method::RSBred:
+            case Method::FRLGBred:
+                return state.getGenerateAdvance();
+            default:
+                return state.getAdvances();
+            }
```
Comment (Admiral-Fish) [inline Source/Forms/Models/Gen3/EggModel3.cpp:72]: I am not a big fan of this approach. It would be best to modify getColumn and the QStringList holding all the strings if necessary. This way we only do the switch statement once.

**Review by Admiral-Fish — CHANGES_REQUESTED** [review]

File: Source/Forms/Models/Gen3/EggModel3.cpp (hunk 1 above)
Comment (Real96) [reply Source/Forms/Models/Gen3/EggModel3.cpp]: > I am not a big fan of this approach. It would be best to modify getColumn and the QStringList holding all the strings if necessary. This way we only do the switch statement once.

Changed
